
[build]
  publish = "public"
  command = "hugo --gc --minify"


[build.environment]
  HUGO_VERSION = "0.83.0"

[context.production.environment]
  HUGO_VERSION = "0.83.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
